"""
dgmh/scripts/smoke_loop.py — Full mock-cycle smoke driver (W5 deliverable).

Runs one complete DGM-H iteration with:
  - mock modifier (no real Codex call)
  - mock critic   (no real Codex call)
  - REAL bias detector
  - REAL run log  (writes to a temp file by default; pass --runs-path to persist)

Lets an operator see one complete cycle's output without invoking real Codex.
NOT run under pytest (guarded by __main__ check and pytest module guard).

Usage:
    python -m dgmh.scripts.smoke_loop [--verbose] [--runs-path <path>]

Env:
    HERMES_HOME — override ~/.hermes home (default: ~/.hermes)
"""

from __future__ import annotations

import argparse
import logging
import sys
import tempfile
from pathlib import Path

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------

_HERMES_ROOT = Path(__file__).parent.parent.parent
if str(_HERMES_ROOT) not in sys.path:
    sys.path.insert(0, str(_HERMES_ROOT))

# ---------------------------------------------------------------------------
# Pytest guard — module-level import is safe; execution is __main__-only
# ---------------------------------------------------------------------------

_UNDER_PYTEST = "pytest" in sys.modules


def _build_mock_archive() -> list:
    """Build a small in-memory archive of Generation-like objects."""
    from dgmh.select_parents import Generation

    return [
        Generation(
            id="coding/hello-world",
            score=0.65,
            compiled_children=1,
            generation_index=0,
            selectable=True,
            extra={
                "skill_path": "",
                "lineage": [],
                "skill_md": "---\nname: hello-world\ncategory: coding\n---\nA simple hello-world skill.\n",
            },
        ),
        Generation(
            id="coding/fizzbuzz",
            score=0.72,
            compiled_children=0,
            generation_index=1,
            selectable=True,
            extra={
                "skill_path": "",
                "lineage": ["coding/hello-world"],
                "skill_md": "---\nname: fizzbuzz\ncategory: coding\n---\nFizzBuzz implementation skill.\n",
            },
        ),
        Generation(
            id="coding/sort-list",
            score=0.70,
            compiled_children=0,
            generation_index=2,
            selectable=True,
            extra={
                "skill_path": "",
                "lineage": ["coding/hello-world"],
                "skill_md": "---\nname: sort-list\ncategory: coding\n---\nSort a list of items skill.\n",
            },
        ),
    ]


class _MockModifier:
    """Mock modifier — returns a fixed SkillCandidate without calling Codex."""

    def modify(self, parent, archive):
        from dgmh.modifier import SkillCandidate

        child_md = (
            "---\n"
            f"name: {parent.id.split('/')[-1]}-v2\n"
            f"category: {parent.id.split('/')[0]}\n"
            "version: 2\n"
            "---\n"
            "# Mock child skill\n\n"
            f"Derived from parent `{parent.id}` by smoke_loop mock modifier.\n"
            "This text was not generated by real Codex.\n"
        )
        return SkillCandidate(
            skill_id=f"{parent.id}-v2",
            skill_md=child_md,
            lineage=list(parent.extra.get("lineage", [])) + [parent.id]
            if isinstance(parent.extra, dict) else [parent.id],
            attempt=1,
            raw_codex_output='{"mutation": "mock"}',
        )


class _MockCritic:
    """Mock critic — always approves."""

    def review(self, candidate, parent, archive):
        from dgmh.critic import CriticReview

        return CriticReview(
            verdict="approve",
            reason="mock critic always approves",
            elapsed_ms=0,
        )


def run_smoke_loop(
    verbose: bool = False,
    runs_path: str | None = None,
) -> None:
    """Run one full mock iteration cycle and print results."""
    logger = logging.getLogger("smoke_loop")

    # Temp runs.jsonl if not specified
    tmp_dir_obj = None
    if runs_path is None:
        tmp_dir_obj = tempfile.TemporaryDirectory()
        runs_path = str(Path(tmp_dir_obj.name) / "runs.jsonl")
        logger.info("Using temp runs.jsonl at: %s", runs_path)
    else:
        logger.info("Using runs.jsonl at: %s", runs_path)

    try:
        archive = _build_mock_archive()
        modifier = _MockModifier()
        critic = _MockCritic()

        from dgmh.loop import IterationOpts, run_one_iteration

        opts = IterationOpts(
            seed_archive=archive,
            modifier=modifier,
            critic=critic,
            seed=42,
            parents_per_iter=1,
            runs_jsonl_path=runs_path,
            # Use a temp archive path too (smoke test doesn't write real skills)
            archive_jsonl_path=str(Path(runs_path).parent / "archive.jsonl"),
        )

        logger.info("Running one mock DGM-H iteration...")
        result = run_one_iteration(opts)

        # Print iteration result
        print("\n" + "=" * 70)
        print("SMOKE LOOP RESULT — one mock DGM-H iteration")
        print("=" * 70)
        print(f"accepted        : {result.accepted}")
        print(f"rejection_reason: {result.rejection_reason}")
        if result.parent:
            print(f"parent          : {result.parent.id} (score={result.parent.score:.3f})")
        if result.candidate:
            print(f"candidate       : {result.candidate.skill_id}")
        print()

        # Print bias report from run_record
        rr = result.run_record
        b = rr.bias
        print("Bias summary (from REAL bias detector):")
        print(f"  inspected_generations : {b.inspected_generations}")
        print(f"  signal_count          : {b.signal_count}")
        print(f"  severities            : {b.severities}")
        print()

        # Print maturity check on the temp file
        print("Maturity check output (REAL maturity_check on temp runs.jsonl):")
        print("-" * 50)
        from dgmh.maturity_check import (
            compute_metrics,
            evaluate_gate,
            format_report,
        )
        from dgmh.run_log import read_run_records
        from datetime import datetime, timezone

        records = read_run_records(runs_path)
        window_days = 28
        now_dt = datetime.now(timezone.utc)
        cutoff_ts = now_dt.timestamp() - window_days * 24 * 3600
        window_records = [
            r for r in records
            if datetime.fromisoformat(r.recorded_at).timestamp() >= cutoff_ts
        ]
        metrics = compute_metrics(window_records)
        verdict, reasons = evaluate_gate(metrics, window_days)
        report = format_report(
            metrics=metrics,
            verdict=verdict,
            reasons=reasons,
            window_days=window_days,
            window_start=datetime.fromtimestamp(cutoff_ts, tz=timezone.utc),
            window_end=now_dt,
            verbose=verbose,
            window_records=window_records,
        )
        print(report)
        print("-" * 50)
        print()
        print("Bias envelope JSON (Codex-shape):")
        from dgmh.bias_detector import make_heuristic_skill_bias_detector

        detector = make_heuristic_skill_bias_detector()
        bias_report = detector.detect(archive, context_note="smoke-loop")
        print(bias_report.envelope_json)
        print("=" * 70)
        print("Smoke loop complete. No real Codex was called.")

    finally:
        if tmp_dir_obj is not None:
            tmp_dir_obj.cleanup()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="DGM-H W5 smoke loop: one mock cycle (no real Codex)"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Include per-run details in maturity report",
    )
    parser.add_argument(
        "--runs-path",
        default=None,
        help="Path for runs.jsonl (default: temp file, deleted after run)",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    run_smoke_loop(verbose=args.verbose, runs_path=args.runs_path)


if __name__ == "__main__":
    if _UNDER_PYTEST:
        print("smoke_loop: skipped (running under pytest)", file=sys.stderr)
        sys.exit(0)
    main()
